#!/usr/bin/env bash

ip link add br0 type bridge
ip addr flush dev enp0s20u2
ip link set enp0s20u2 master br0
systemctl restart dhcpcd
ip tuntap add mode tap tap0
ip link set tap0 master br0
ip link set dev br0 up
ip link set dev tap0 up

